[project]
name = "federated-lora"
version = "0.1.0"
description = "A harness for fine-tuning methods using LoRA under federated machine learning"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.0",
    "huggingface-hub>=1.23.0",
    "matplotlib>=3.10.0",
    "peft>=0.19.1",
    "transformers>=5.13.1",
]

[dependency-groups]
dev = [
    "ruff>=0.16.0",
]

[tool.ruff]
# Set the maximum line length to 79.
line-length = 79

[tool.ruff.lint]
select = [
    "E",    # check code against some of the style conventions in PEP 8
    "F",    # checks Python source files for errors
    "W",    # warnings
    "I",    # sort imports alphabetically and automatically separate into sections and by type
    "UP",   # upgrade syntax for newer versions of Python
    "B",    # find likely bugs and design problems
    "SIM",  # simplify code
    "C4",   # write better list/set/dict comprehensions
    "NPY",  # numpy-specific rules
    "RUF",  # ruff's own rules
]
extend-select = [
    "E501",
]
ignore = [
    "E741", # ambigious file names 
    "F401", # re-exports
    
]

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true    # format code examples in docstrings
